# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'manage.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QPushButton,
    QRadioButton, QSizePolicy, QSpinBox, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1461, 848)
        self.main_table = QTableWidget(Form)
        if (self.main_table.columnCount() < 9):
            self.main_table.setColumnCount(9)
        self.main_table.setObjectName(u"main_table")
        self.main_table.setGeometry(QRect(400, 20, 1051, 801))
        font = QFont()
        font.setPointSize(12)
        self.main_table.setFont(font)
        self.main_table.setRowCount(0)
        self.main_table.setColumnCount(9)
        self.main_table.horizontalHeader().setVisible(True)
        self.main_table.horizontalHeader().setCascadingSectionResizes(True)
        self.main_table.horizontalHeader().setDefaultSectionSize(100)
        self.main_table.horizontalHeader().setStretchLastSection(True)
        self.main_table.verticalHeader().setVisible(True)
        self.sort_control_groupbox = QGroupBox(Form)
        self.sort_control_groupbox.setObjectName(u"sort_control_groupbox")
        self.sort_control_groupbox.setGeometry(QRect(10, 130, 381, 121))
        self.sort_control_groupbox.setFont(font)
        self.sort_ref_combobox = QComboBox(self.sort_control_groupbox)
        self.sort_ref_combobox.setObjectName(u"sort_ref_combobox")
        self.sort_ref_combobox.setGeometry(QRect(40, 30, 191, 22))
        self.label_4 = QLabel(self.sort_control_groupbox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 31, 21))
        self.label_4.setFont(font)
        self.sort_mode_combobox = QComboBox(self.sort_control_groupbox)
        self.sort_mode_combobox.setObjectName(u"sort_mode_combobox")
        self.sort_mode_combobox.setGeometry(QRect(240, 30, 68, 22))
        self.label_5 = QLabel(self.sort_control_groupbox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(323, 30, 41, 21))
        self.label_5.setFont(font)
        self.sort_enter_btn = QPushButton(self.sort_control_groupbox)
        self.sort_enter_btn.setObjectName(u"sort_enter_btn")
        self.sort_enter_btn.setGeometry(QRect(240, 60, 121, 41))
        self.file_groupbox = QGroupBox(Form)
        self.file_groupbox.setObjectName(u"file_groupbox")
        self.file_groupbox.setGeometry(QRect(10, 10, 381, 111))
        self.file_groupbox.setFont(font)
        self.readfile_btn = QPushButton(self.file_groupbox)
        self.readfile_btn.setObjectName(u"readfile_btn")
        self.readfile_btn.setGeometry(QRect(20, 40, 111, 41))
        self.readfile_btn.setFont(font)
        self.savefile_btn = QPushButton(self.file_groupbox)
        self.savefile_btn.setObjectName(u"savefile_btn")
        self.savefile_btn.setGeometry(QRect(160, 40, 111, 41))
        self.savefile_btn.setFont(font)
        self.data_groupbox = QGroupBox(Form)
        self.data_groupbox.setObjectName(u"data_groupbox")
        self.data_groupbox.setGeometry(QRect(10, 260, 381, 461))
        self.data_groupbox.setFont(font)
        self.label_6 = QLabel(self.data_groupbox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 30, 54, 21))
        self.label_7 = QLabel(self.data_groupbox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 60, 54, 21))
        self.label_8 = QLabel(self.data_groupbox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 90, 54, 21))
        self.mode_add_radiobtn = QRadioButton(self.data_groupbox)
        self.mode_add_radiobtn.setObjectName(u"mode_add_radiobtn")
        self.mode_add_radiobtn.setGeometry(QRect(80, 30, 61, 21))
        self.mode_edit_radiobtn = QRadioButton(self.data_groupbox)
        self.mode_edit_radiobtn.setObjectName(u"mode_edit_radiobtn")
        self.mode_edit_radiobtn.setGeometry(QRect(150, 30, 61, 21))
        self.mode_edit_radiobtn.setChecked(True)
        self.groupBox_2 = QGroupBox(self.data_groupbox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 190, 341, 211))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 30, 111, 21))
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 60, 111, 21))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 90, 111, 21))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 120, 111, 21))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 150, 111, 21))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 180, 111, 21))
        self.all_perf_edit = QLineEdit(self.groupBox_2)
        self.all_perf_edit.setObjectName(u"all_perf_edit")
        self.all_perf_edit.setGeometry(QRect(120, 150, 181, 21))
        self.all_perf_edit.setReadOnly(True)
        self.all_perf_rank_edit = QLineEdit(self.groupBox_2)
        self.all_perf_rank_edit.setObjectName(u"all_perf_rank_edit")
        self.all_perf_rank_edit.setGeometry(QRect(120, 180, 181, 21))
        self.all_perf_rank_edit.setReadOnly(True)
        self.quarter1_perf_spinbox = QSpinBox(self.groupBox_2)
        self.quarter1_perf_spinbox.setObjectName(u"quarter1_perf_spinbox")
        self.quarter1_perf_spinbox.setGeometry(QRect(120, 30, 181, 22))
        self.quarter2_perf_spinbox = QSpinBox(self.groupBox_2)
        self.quarter2_perf_spinbox.setObjectName(u"quarter2_perf_spinbox")
        self.quarter2_perf_spinbox.setGeometry(QRect(120, 60, 181, 22))
        self.quarter3_perf_spinbox = QSpinBox(self.groupBox_2)
        self.quarter3_perf_spinbox.setObjectName(u"quarter3_perf_spinbox")
        self.quarter3_perf_spinbox.setGeometry(QRect(120, 90, 181, 22))
        self.quarter4_perf_spinbox = QSpinBox(self.groupBox_2)
        self.quarter4_perf_spinbox.setObjectName(u"quarter4_perf_spinbox")
        self.quarter4_perf_spinbox.setGeometry(QRect(120, 120, 181, 22))
        self.id_edit = QLineEdit(self.data_groupbox)
        self.id_edit.setObjectName(u"id_edit")
        self.id_edit.setGeometry(QRect(80, 60, 171, 21))
        self.name_edit = QLineEdit(self.data_groupbox)
        self.name_edit.setObjectName(u"name_edit")
        self.name_edit.setGeometry(QRect(80, 90, 171, 21))
        self.edit_enter_btn = QPushButton(self.data_groupbox)
        self.edit_enter_btn.setObjectName(u"edit_enter_btn")
        self.edit_enter_btn.setGeometry(QRect(70, 410, 75, 31))
        self.edit_del_btn = QPushButton(self.data_groupbox)
        self.edit_del_btn.setObjectName(u"edit_del_btn")
        self.edit_del_btn.setGeometry(QRect(154, 410, 121, 31))
        self.edit_cancel_btn = QPushButton(self.data_groupbox)
        self.edit_cancel_btn.setObjectName(u"edit_cancel_btn")
        self.edit_cancel_btn.setGeometry(QRect(280, 410, 75, 31))
        self.gender_groupbox = QGroupBox(self.data_groupbox)
        self.gender_groupbox.setObjectName(u"gender_groupbox")
        self.gender_groupbox.setGeometry(QRect(20, 120, 231, 61))
        self.male_radiobtn = QRadioButton(self.gender_groupbox)
        self.male_radiobtn.setObjectName(u"male_radiobtn")
        self.male_radiobtn.setGeometry(QRect(20, 30, 61, 21))
        self.female_radiobtn = QRadioButton(self.gender_groupbox)
        self.female_radiobtn.setObjectName(u"female_radiobtn")
        self.female_radiobtn.setGeometry(QRect(120, 30, 61, 21))
        self.search_groupbox = QGroupBox(Form)
        self.search_groupbox.setObjectName(u"search_groupbox")
        self.search_groupbox.setGeometry(QRect(10, 730, 381, 91))
        self.search_groupbox.setFont(font)
        self.label = QLabel(self.search_groupbox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 61, 21))
        self.label_2 = QLabel(self.search_groupbox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 60, 61, 21))
        self.id_search_edit = QLineEdit(self.search_groupbox)
        self.id_search_edit.setObjectName(u"id_search_edit")
        self.id_search_edit.setGeometry(QRect(80, 30, 201, 21))
        self.search_id_btn = QPushButton(self.search_groupbox)
        self.search_id_btn.setObjectName(u"search_id_btn")
        self.search_id_btn.setGeometry(QRect(290, 30, 75, 24))
        self.quarter_select_combobox = QComboBox(self.search_groupbox)
        self.quarter_select_combobox.setObjectName(u"quarter_select_combobox")
        self.quarter_select_combobox.setGeometry(QRect(80, 60, 201, 22))
        self.query_quarter_btn = QPushButton(self.search_groupbox)
        self.query_quarter_btn.setObjectName(u"query_quarter_btn")
        self.query_quarter_btn.setGeometry(QRect(290, 60, 75, 24))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u5458\u5de5\u4e1a\u7ee9\u7ba1\u7406", None))
        self.sort_control_groupbox.setTitle(QCoreApplication.translate("Form", u"\u6392\u5e8f", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u6309", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u6392\u5e8f", None))
        self.sort_enter_btn.setText(QCoreApplication.translate("Form", u"\u5e94\u7528", None))
        self.file_groupbox.setTitle(QCoreApplication.translate("Form", u"\u6587\u4ef6", None))
        self.readfile_btn.setText(QCoreApplication.translate("Form", u"\u8bfb\u53d6", None))
        self.savefile_btn.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58", None))
        self.data_groupbox.setTitle(QCoreApplication.translate("Form", u"\u6dfb\u52a0/\u4fee\u6539\u6570\u636e", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u6a21\u5f0f\uff1a", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u5de5\u53f7\uff1a", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u59d3\u540d\uff1a", None))
        self.mode_add_radiobtn.setText(QCoreApplication.translate("Form", u"\u6dfb\u52a0", None))
        self.mode_edit_radiobtn.setText(QCoreApplication.translate("Form", u"\u4fee\u6539", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"\u4e1a\u7ee9", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\u7b2c\u4e00\u5b63\u5ea6\uff1a", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u7b2c\u4e8c\u5b63\u5ea6\uff1a", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"\u7b2c\u4e09\u5b63\u5ea6\uff1a", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"\u7b2c\u56db\u5b63\u5ea6\uff1a", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"\u603b\u4e1a\u7ee9\uff1a", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"\u603b\u4e1a\u7ee9\u6392\u540d\uff1a", None))
        self.edit_enter_btn.setText(QCoreApplication.translate("Form", u"\u786e\u5b9a", None))
        self.edit_del_btn.setText(QCoreApplication.translate("Form", u"\u5220\u9664\u8fd9\u4e2a\u5458\u5de5", None))
        self.edit_cancel_btn.setText(QCoreApplication.translate("Form", u"\u53d6\u6d88", None))
        self.gender_groupbox.setTitle(QCoreApplication.translate("Form", u"\u6027\u522b", None))
        self.male_radiobtn.setText(QCoreApplication.translate("Form", u"\u7537", None))
        self.female_radiobtn.setText(QCoreApplication.translate("Form", u"\u5973", None))
        self.search_groupbox.setTitle(QCoreApplication.translate("Form", u"\u641c\u7d22\u67e5\u8be2", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u5de5\u53f7\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u5b63\u5ea6\uff1a", None))
        self.search_id_btn.setText(QCoreApplication.translate("Form", u"\u641c\u7d22", None))
        self.query_quarter_btn.setText(QCoreApplication.translate("Form", u"\u67e5\u8be2", None))
    # retranslateUi

