# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\workspace\接单\2023\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(322, 217)
        self.lblAccount = QtWidgets.QLabel(LoginForm)
        self.lblAccount.setGeometry(QtCore.QRect(30, 51, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAccount.setFont(font)
        self.lblAccount.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAccount.setObjectName("lblAccount")
        self.lblPassword = QtWidgets.QLabel(LoginForm)
        self.lblPassword.setGeometry(QtCore.QRect(30, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblPassword.setFont(font)
        self.lblPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPassword.setObjectName("lblPassword")
        self.lineAccount = QtWidgets.QLineEdit(LoginForm)
        self.lineAccount.setGeometry(QtCore.QRect(100, 50, 151, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.lineAccount.setFont(font)
        self.lineAccount.setObjectName("lineAccount")
        self.linePassword = QtWidgets.QLineEdit(LoginForm)
        self.linePassword.setGeometry(QtCore.QRect(100, 120, 151, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.linePassword.setFont(font)
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePassword.setObjectName("linePassword")
        self.btnLogin = QtWidgets.QPushButton(LoginForm)
        self.btnLogin.setGeometry(QtCore.QRect(40, 172, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.btnReg = QtWidgets.QPushButton(LoginForm)
        self.btnReg.setGeometry(QtCore.QRect(180, 172, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.btnReg.setFont(font)
        self.btnReg.setObjectName("btnReg")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "登录页面"))
        self.lblAccount.setText(_translate("LoginForm", "账号"))
        self.lblPassword.setText(_translate("LoginForm", "密码"))
        self.btnLogin.setText(_translate("LoginForm", "登录"))
        self.btnReg.setText(_translate("LoginForm", "注册"))
        self.lblAccount.setText(_translate("LoginForm", "账号"))
        self.lblPassword.setText(_translate("LoginForm", "密码"))
        self.btnLogin.setText(_translate("LoginForm", "登录"))
