# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\workspace\接单\2023\Reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegForm(object):
    def setupUi(self, RegForm):
        RegForm.setObjectName("RegForm")
        RegForm.resize(400, 300)
        self.lblReg = QtWidgets.QLabel(RegForm)
        self.lblReg.setGeometry(QtCore.QRect(160, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.lblReg.setFont(font)
        self.lblReg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblReg.setObjectName("lblReg")
        self.lblAccount = QtWidgets.QLabel(RegForm)
        self.lblAccount.setGeometry(QtCore.QRect(43, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.lblAccount.setFont(font)
        self.lblAccount.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAccount.setObjectName("lblAccount")
        self.lineAccount = QtWidgets.QLineEdit(RegForm)
        self.lineAccount.setGeometry(QtCore.QRect(130, 80, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.lineAccount.setFont(font)
        self.lineAccount.setObjectName("lineAccount")
        self.lblPwd = QtWidgets.QLabel(RegForm)
        self.lblPwd.setGeometry(QtCore.QRect(43, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.lblPwd.setFont(font)
        self.lblPwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPwd.setObjectName("lblPwd")
        self.linePwd = QtWidgets.QLineEdit(RegForm)
        self.linePwd.setGeometry(QtCore.QRect(130, 150, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.linePwd.setFont(font)
        self.linePwd.setObjectName("linePwd")
        self.btnReg = QtWidgets.QPushButton(RegForm)
        self.btnReg.setGeometry(QtCore.QRect(150, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.btnReg.setFont(font)
        self.btnReg.setObjectName("btnReg")

        self.retranslateUi(RegForm)
        QtCore.QMetaObject.connectSlotsByName(RegForm)

    def retranslateUi(self, RegForm):
        _translate = QtCore.QCoreApplication.translate
        RegForm.setWindowTitle(_translate("RegForm", "Form"))
        self.lblReg.setText(_translate("RegForm", "注册窗口"))
        self.lblAccount.setText(_translate("RegForm", "账号"))
        self.lblPwd.setText(_translate("RegForm", "密码"))
        self.btnReg.setText(_translate("RegForm", "注册"))
